-- DROP ALL TABLES
DROP TABLE ACTOR_ROLES;
DROP TABLE DIRECTS;
DROP TABLE LIKES_TOPICS;
DROP TABLE MOVIE_CASTS;
DROP TABLE MOVIE_RATINGS;
DROP TABLE MOVIE_ROLES;
DROP TABLE MOVIE_TOPICS;
DROP TABLE PROFILES;
DROP TABLE SPONSORS;
DROP TABLE USED_DEVICES;
-- DROP TABLE USERS;
DROP TABLE ACTORS;
DROP TABLE CASTING_TYPES;
DROP TABLE DEVICES;
DROP TABLE DIRECTORS;
DROP TABLE MOVIES;
DROP TABLE ROLES;
DROP TABLE STUDIOS;
DROP TABLE TOPICS;
-- DROP TABLE USER_TYPES;



-- DELETE ALL ROWS FROM TABLES
DELETE FROM ACTOR_ROLES;
DELETE FROM DIRECTS;
DELETE FROM LIKES_TOPICS;
DELETE FROM MOVIE_CASTS;
DELETE FROM MOVIE_RATINGS;
DELETE FROM MOVIE_ROLES;
DELETE FROM MOVIE_TOPICS;
DELETE FROM PROFILES;
DELETE FROM SPONSORS;
DELETE FROM USED_DEVICES;
-- DELETE FROM USERS;
DELETE FROM ACTORS;
DELETE FROM CASTING_TYPES;
DELETE FROM DEVICES;
DELETE FROM DIRECTORS;
DELETE FROM MOVIES;
DELETE FROM ROLES;
DELETE FROM STUDIOS;
DELETE FROM TOPICS;
-- DELETE FROM USER_TYPES;